"""bge-m3 migration: resize situated_embeddings.vector 384 → 1024.

Drops the HNSW index, clears situated_embeddings and obs_embeddings (data
will be regenerated by the re-embedding step), alters the vector column to
vector(1024), and recreates the HNSW index.

Run after: 2026-06-29-019_purge_utterance_duplicates.py
"""
from __future__ import annotations


def upgrade(conn) -> None:
    with conn.cursor() as cur:
        cur.execute("DROP INDEX IF EXISTS idx_se_hnsw")
        cur.execute("TRUNCATE TABLE situated_embeddings")
        cur.execute("TRUNCATE TABLE obs_embeddings")
        cur.execute("ALTER TABLE situated_embeddings DROP COLUMN vector")
        cur.execute(
            "ALTER TABLE situated_embeddings ADD COLUMN vector vector(1024) NOT NULL"
        )
        cur.execute(
            "CREATE INDEX idx_se_hnsw ON situated_embeddings "
            "USING hnsw (vector vector_cosine_ops)"
        )
